### PR TITLE
Add RS-68 & RS-68B from BDB & Zorg. (On Hold Indefinitely)

### PR DESCRIPTION
**Pull request by vader111**
Add RS-68 & RS-68B from BDB

### CODE REVIEW

**Comment by zorg2044** [comment]
https://www.dropbox.com/s/r03thl331zy8nh2/Bluedog_DeltaIV_RS68.dds?dl=0

Alternate texture which replaces the cyrillic with English.

**Comment by vader111** [comment]
(Ready To Review)

**Comment by Capkirk123** [comment]
Surface attachment is disabled (should be enabled). The verniers have the same plume as the main engine, and the fixed vernier appears to gimbal even though it shouldn't.

**Comment by vader111** [comment]
@Capkirk123 Testing Fixes Now

**Comment by vader111** [comment]
@Capkirk123 Should be Fixed now

**Comment by vader111** [comment]
Don't have the time to fix the model to finish this

**Pull request closed without merging**
