### PR TITLE
More Engines and updates

### PR DESCRIPTION
**Pull request by Capkirk123**
A huge patch, with lots of engines and new models. RN models have been removed and replaced with alternatives where possible.

Replaced Models:

- Castor-1: RN model replaced with BDB model

- Castor-2: RN model replaced with BDB model

- H-1C: SSTU model replaced with BDB model

- H-1D: SSTU model replaced with BDB model

- LR87: RN model replaced with BDB model

- LR91: RN model replaced with BDB model

New Engines:

- Algol 1 radial and inline added from BDB

- Algol 2 radial and inline added from BDB

- Antares 1 added from BDB

- Antares 2 added from BDB

- Castor-4 added from BDB

- Castor-4AXL added from BDB

- Castor-30 added from BDB

- Castor-30XL added from BDB

- Castor-120 added from BDB

- F-1B added from SSTU

- LR87 Single added from BDB

- LR87LH2 added from BDB

- RD-0120 added from Real Engines

- RD-0124 added from Real Engines

- RD-0146 added from Real Engines

- RD-0210 added from Real Engines

- RD-0212 added from Real Engines

- XLR11 added using modified Taerobee model

Other parts

- Castor 1 & 2 decoupler added

### CODE REVIEW

**Comment by lpgagnon** [comment]
Trying out the XLR11, noticing some bits missing in its SPH PAW compared to the taerobee version:
- no ignition count
- no propellant state
- no Flow Priority buttons

In actual use, the first config doesn't require HP tanks; and the part appears to have infinite ignitions.

Does this PR need an RO counterpart to work correctly?

**Comment by Capkirk123** [comment]
That is really odd, it uses the same global config that the Taerobee XLR11 does. I'll look into it

**Comment by jwvanderbeck** [comment]
Been testing this as well for quite some time in my previous save and only ran into some minor issues which were addressed already.

This should be pretty good to go, no?

**Comment by jwvanderbeck** [comment]
Is there anything stopping this from being merged?

**Pull request merged**
