### PR TITLE
Fix up ROEngine Patches to stop it disabling ROCapsule Engines. (Ready To Review)

### PR DESCRIPTION
**Pull request by vader111**
Fix up ROEngine Patches to stop it disabling ROCapsule Engines that will affect my Pull Requests.

### CODE REVIEW

**Comment by vader111** [comment]
Stops The Patching Disabling Engines for https://github.com/KSP-RO/ROCapsules/pull/69 & https://github.com/KSP-RO/ROCapsules/pull/66

**Comment by vader111** [comment]
(Ready To Review)

**Comment by Capkirk123** [comment]
Looks good, although I question whether some of these changes are necessary. The current AJ10 Adv. model fits just fine on the GE Apollo last I checked (and the GE Apollo AJ10 has many issues with poorly placed transforms and colliders).

**Comment by vader111** [comment]
@Capkirk123 should be fixed now

**Comment by siimav** [comment]
Should rebase it to master now

**Comment by vader111** [comment]
> Should rebase it to master now

sorry what?

**Pull request closed without merging**
