### PR TITLE
Add nozzle glow to Hydrolox engines

### PR DESCRIPTION
**Pull request by lukecologne**
The BE-3 from NicheParts and the RD-0120 needed a Re-Export from Unity. In the process, I also converted the textures of the RD0120 to DDS.

Requires https://github.com/KSP-RO/ROLibrary/pull/7

A few examples:

RS-25
screenshot6
J-2
screenshot7
RL10 B-2
screenshot8

### CODE REVIEW

**Comment by DRVeyl** [comment]
Assumed this was still in draft awaiting the ROLib PR.  Any updates?

**Comment by lukecologne** [comment]
You are correct, and yes, it still needs a bit of tweaking.

**Comment by DRVeyl** [comment]
Been a few months, want to check back in on this.

**Comment by lukecologne** [comment]
Yeah, sorry for not having this done already, uni stuff came inbetween and i'm currently in exam phase. In principle, it should be working, but the colors are just some more or less random shades of white/blue and are a little bit too bright for my taste. But, since I might not have much time to tweak stuff, I could do a quick check if it is still working (but i don't see why not), and someone else could tweak if they like

**Comment by DRVeyl** [comment]
I think it would be reasonable to commit if you think the current settings are close enough.  Get more folks using them and if they need to be fine-tuned, can always make a change.

**Comment by lukecologne** [comment]
Alright, quickly launched KSP and tested a few engines, seems to be working nicely. I'll mark it as ready then

**Pull request merged**
