### PR TITLE
Add Waterfall configs for the liquid rocket engines.

### PR DESCRIPTION
**Pull request by vevladdd**
This pull request by @al2me6 and me adds Waterfall configs, new sounds and bigger gas generator exhausts for the engines.
Requires and meant to be used with [this PR.](https://github.com/KSP-RO/RealismOverhaul/pull/2430)
More information and the full list of configured engines: [ROE-Waterfall](https://github.com/vevladdd/ROE-Waterfall) and [Add a Waterfall patching system](https://github.com/KSP-RO/RealismOverhaul/pull/2430).

Please, merge this PR only after the PR with the processor system is merged.

### CODE REVIEW

**Comment by NathanKell** [comment]
Now that https://github.com/KSP-RO/RealismOverhaul/pull/2430 is in, are we good to go here?

**Comment by al2me6** [comment]
I believe there's one more change that needs to make its way here, but otherwise yes.

**Comment by NathanKell** [comment]
Ok!

**Comment by vevladdd** [comment]
I think it is ready now!

**Pull request merged**
