### PR TITLE
Update Plumes

### PR DESCRIPTION
**Pull request by Capkirk123**
Update plumes with new plumes from RealPlume. All Hydrolox engines get new wispy red plumes, the E-1 gets TP exhaust plume, and the F-1 gets a skirt cooling plume. Also update some plumes that lukecolonge missed.

### CODE REVIEW

**Comment by siimav** [comment]
Has whitespace issues

**Comment by lukecologne** [comment]
Also, you are changing F-1. E-1 and gamma plumes in a hydrolox plume PR? And second, take a look in the #dev-feedback channel, I've come up with some emissives

**Comment by Capkirk123** [comment]
Fixed whitespce, updated description

**Comment by siimav** [comment]
What's the status of this PR? Is Luke still working on better plumes for those engines?

**Comment by lukecologne** [comment]
Why are you removing the existing plumes on the E-1 and replace it with essentially the same one? If you just want to add a Turbopump exhaust, you can do so with the existing plumes. The same goes for the F-1, the film cooling plume can be added in parallel to the plume template. Also, you can remove the additional flares on the hydrolox engines, as I plan to add emissives for those. I already got the RS-68 and RS-25 done.

**Comment by Capkirk123** [comment]
The existing plumes were removed because I couldn't get multiple plumes per engine working with the plume template system, the plumes should be exactly the same though, I copied the settings over. I would prefer to keep the flares and emissives, it adds a little more depth and color to the plumes, but I can remove them if you want.

**Comment by lukecologne** [comment]
It is definetely possible to do a Multi-Plume setup with the template system. It set's the engine up by default, if you add a `setupEngine=false` to the template, it doesn't set it up, and you can do it manually, just as if it were a normal plume. See https://github.com/KSP-RO/ROEngines/blob/61a003dc7f542cc40488d902553f38d04dc1ee76/GameData/ROEngines/RealPlume/Merlin_SSTU_RealPlume.cfg#L1-L36

**Comment by lukecologne** [comment]
About the flares: I'll take your branch and test the flares with emissives and post some pictures, and then we can see what looks nice

**Pull request merged**
